# Generated by Django 4.2.4 on 2023-08-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='clase',
            field=models.CharField(choices=[('Permiso', 'Permiso'), ('Rol', 'Rol'), ('User', 'User'), ('Cliente', 'Cliente'), ('Reserva', 'Reserva'), ('Ticket', 'Ticket'), ('Boleta', 'Boleta'), ('TipoCancha', 'TipoCancha'), ('Cancha', 'Cancha'), ('Horario', 'Horario'), ('Agenda', 'Agenda')], max_length=15),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='permiso',
            unique_together={('clase', 'nombre')},
        ),
    ]
